### ISSUE TITLE
GStreamer; Unable to pause and Error: "No URI handler implemented for \"http\"."

### ISSUE THREAD

**Issue by Hi-Phile** [0x0is1/iptv-desktop#1]
I am running Arch Linux from RebornOS distro.
System:
  Host: thinkuser-a10 Kernel: 5.19.13-arch1-1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.25.5 Distro: RebornOS Linux

iptv-desktop does launch and open, but when I attempt to display the video, it's just blank.
Seeing the following errors after starting up iptv-desktop and attempting to connect and stream from any valid m3u8 URL.:

GStreamer; Unable to pause - "https://gizmeon.s.llnwi.net/channellivev3/live/master.m3u8?channel=275"
Error: "No URI handler implemented for \"https\"."

I researched and saw that this message appears to due some problem with GStreamer library version 1.20.  I haven't tried GStreamer v 1.18 but I'm mostly certain it is due this regression.

$ sudo pacman -Qs gstreamer
[sudo] password for thinkuser: 
local/gstreamer 1.20.3-2
    Multimedia graph framework - core
local/phonon-qt5-gstreamer 4.10.0-3
    Phonon GStreamer backend for Qt5

Here's the other discussion which might be related or is the cause of this error:
https://github.com/openframeworks/openFrameworks/issues/6871

Here's a screen capture, I can show you that the video does play in a web browser, but not in the iptv-desktop player:
![image](https://user-images.githubusercontent.com/35350630/195724145-193e2c3c-314f-42a5-82aa-1dbf46500f61.png)

**Comment by 0x0is1** [comment]
# Thanks for this feedback.

## Problem Analysis
- As per this [another repo issue](https://github.com/strawberrymusicplayer/strawberry/issues/142) indicates, This issue is faced by mainly Arch system.
- And [a comment](https://github.com/openframeworks/openFrameworks/issues/6871#issuecomment-1272506182) from issue mentioned above in your feedback verifies that `gstreamer 1.20.3`  has resolved the issue on *Debian distros*.
- It is working fine with version `1.20.3` on my debian system.

```css
>> gst-launch-1.0 --version
gst-launch-1.0 version 1.20.3
GStreamer 1.20.3
http://packages.qa.debian.org/gstreamer1.0
```
![image](https://user-images.githubusercontent.com/42772562/195773491-bb1a7696-9e52-462d-94f3-e17218b08d28.png)

## Solution
- I would like to suggest trying this again on the previous version.
- There may be an issue in plugin `gst-plugins-good` or `gstreamer1.0-plugins-good` (In debian), So cross verify once if that is not the case, and it is correctly installed.
- There might be a minor bug in the GUI too. All you have to do is, try pausing and playing it several times and it may work miraculously (Not sure in this situation)

## Further Steps
- I would love to hear feedback after changes suggested. and just for the mutual comfort, Would you like to test it with Arch on docker and provide the [container](https://github.com/Screenly/screenly-ose/blob/master/webview/Dockerfile)?

**Comment by Hi-Phile** [comment]
I went back to check what the problem was, turns out missing some Arch gst-libs.  I already had gst-libs 1.20.4, but I checked to see what other gst-libs were present:
```
$ sudo pacman -Qq | grep gst
[sudo] password for user: 
gst-libav
gst-plugins-bad-libs
gst-plugins-base
gst-plugins-base-libs
gstreamer
phonon-qt5-gstreamer
```
So I went ahead and installed the gst-python, gst-plugins-ugly gst-plugins-good with their dependencies:
```gst-python-1.20.4-1-x86_64  
 libsidplay-1.36.59-10-x86_64  
 libshout-1:2.4.6-1-x86_64 
 libdv-1.0.0-9-x86_64   
 wavpack-5.5.0-1-x86_64     
 aalib-1.4rc5-14-x86_64   
 gst-plugins-ugly-1.20.4-1-x86_64   
 gst-plugins-good-1.20.4-1-x86_64  
 $ sudo pacman -Qq | grep gst
gst-libav
gst-plugins-bad-libs
gst-plugins-base
gst-plugins-base-libs
gst-plugins-good
gst-plugins-ugly
gst-python
gstreamer
phonon-qt5-gstreamer
 ```
But then it still wasn't working, same black screen but now a different error:
```Warning: "No decoder available for type 'application/x-hls'."
Error: "Your GStreamer installation is missing a plug-in."
Warning: "No decoder available for type 'application/x-hls'."
Error: "Your GStreamer installation is missing a plug-in."
```
So, finally installed gst-plugins-bad and then it started working.  
```
$ sudo pacman -S gst-plugins-bad
resolving dependencies...
looking for conflicting packages...

Packages (20) chromaprint-1.5.1-4  faac-1.30-3  gssdp-1.4.0.1-1  gupnp-1:1.4.3-1  gupnp-igd-1.2.0-2  libavtp-0.2.0-1
              libdvdnav-6.1.1-1  libkate-0.4.1-8  liblrdf-0.6.1-4  libltc-1.3.2-1  libmicrodns-0.2.0-1  libnice-0.1.19-1
              libsrtp-1:2.4.2-1  mjpegtools-2.2.1-1  raptor-2.0.15-20  soundtouch-2.3.1-2  spandsp-0.0.6-3  wildmidi-0.4.4-1
              zbar-0.23.90-1  gst-plugins-bad-1.20.4-1
```

So, I think you should add some documentation / note about Arch lib dependencies might be needed.  

Lastly, it's working, but the following is shown:
```
QWidget::paintEngine: Should no longer be called
```
![image](https://user-images.githubusercontent.com/35350630/197411512-f77fe6fe-1648-4cf0-93c8-1015f27c215e.png)

**Comment by 0x0is1** [comment]
Wow, it really did fix the issue. Thanks for your effort.
Instructions for Arch users has been added in commit (https://github.com/0x0is1/iptv-desktop/commit/92efde79a573c5e3ca2c6124e46dee8bff155340).
`QWidget::paintEngine: should no longer be called` issue does not look like affecting the application performance and it must be due to dragging the window of iptv-desktop app. But thanks for calling this out. I will try my best to fix this. Keep up the great work.
Thanks for the contribution again. All the best for your future. You may close the issue now (Please, Do not delete the issue).

**Comment by Hi-Phile** [comment]
This issue is resolved by installing the missing gstreamer and dependent packages, more specifically, gst-plugins-bad is what eventually corrected it.
